# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 톱니바퀴
email: tmp1d@naver.com
description: > # this means to ignore newlines until "baseurl:"
    코드 생산 中
baseurl: "/blog-lab" # the subpath of your site, e.g. /blog
url: #"http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: # jekyllrb
github_username:  kimhjh    # kekyll

# Build settings
markdown: kramdown

# add.
encoding: utf-8
#paginate: 20
#per_page: 20
#paginate_path: "/page:num/"
